version: 0.2

env:
  variables:
    BUILDSPEC: buildspec.yml

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Environment Variables..."
      - printenv
      - pwd
      - pip install --upgrade awscli
      - pip install --upgrade boto3
      - node --version
      - nohup dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo "pre-Build Steps..."
      - $(aws ecr get-login --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
      - printf "Commit - $COMMIT_HASH"
      - printf "Image tag - $IMAGE_TAG"
      - cp api/config/settings.py.sample api/config/settings.py
      - sed -i "s/{DbUser}/$DatabaseUser/" src/config/settings.py
      - sed -i "s/{DbPw}/$DatabasePW/" src/config/settings.py
      - sed -i "s/{DbEndPoint}/$DatabaseEndpoint/" src/config/settings.py
      - sed -i "s/{DbName}/$DbName/" src/config/settings.py
      - sed -i "s/{mailServer}/smtp.gmail.com/" src/config/settings.py
      - sed -i "s/{mailPort}/587/" src/config/settings.py
      - sed -i "s/{timeZone}/America/Santo_Domingo/" src/config/settings.py
      - sed -i "s/{AccessKeyId}/$AccessKeyId/" src/config/settings.py
      - sed -i "s/{SecretAccessKey}/$SecretAccessKey/" src/config/settings.py
      - sed -i "s/{UploadFileBucket}/$AssetsBucket/" src/config/settings.py


  build:
    commands:
      - echo "build steps"
      - IMG_NAME="${ProjectName}:${Realm}"
      - REPO_URI=${AccountId}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMG_NAME}
      - docker build -t ${IMG_NAME} -f docker/prod.Dockerfile .
      - docker tag ${IMG_NAME} ${REPO_URI}
      - cd static
      - npm install webpack-cli -g
      - npm install
      - npm run build

  post_build:
    commands:
      - echo "post-Build Steps..."
      - aws s3 sync public s3://${StaticSiteBucket}
      - docker push ${REPO_URI}

#artifacts:
#
#  files:
#    - inputs/**/*
#  discard-paths: no
