version: 0.2

env:
  variables:
    BUILDSPEC: buildspec.yml

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Environment Variables..."
      - printenv
      - pwd
      - pip install --upgrade awscli
      - pip install --upgrade boto3
      - node --version
      - nohup dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo "pre-Build Steps..."
      - $(aws ecr get-login --no-include-email)
      - IMG_NAME="green-crn-engine"
      - REPO_URI=${AccountId}.dkr.ecr.${AWS_REGION}.amazonaws.com/${Realm}-repository/${IMG_NAME}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
      - printf "Commit - $COMMIT_HASH"
      - printf "Image tag - $IMAGE_TAG"

  build:
    commands:
      - echo "Post build steps"

  post_build:
    commands:
      - echo "post-Build Steps..."

#artifacts:
#
#  files:
#    - inputs/**/*
#  discard-paths: no
