# customer setup required documents per section
DOCUMENTS_SECTION_CLIENT = [
    'CEDULA',
    'RNC',
    'ASAMBLEA',
    'REGISTRO MERCANTIL',
]

DOCUMENTS_SECTION_LEGAL = [
    'TITULO DE PROPIEDAD',
    'CONTRATO DE ALQUILER',
    'FACTURA ELECTRICA',
    'COTIZACIONES', # multiple estimates
    'COTIZACION PFA', # final estimate
    'FORM. CONOCE A TU CLIENTE ENESTAR',
    'FORM. CONOCE A TU CLIENTE ASEGURADORA',
    'CONTRATO DE ENESTAR',
    'CARTA COMPROMISO ITBIS',
    'SERIALES DE EQUIPOS',
    'DOCUMENTO DE RECEPCION DEL SISTEMA',
    'ANEXO LIBRE - NOMBRE/DOCUMENTO',
]

DOCUMENTS_SECTION_DISTRIBUTOR = [
    'ANEXO A',
    'ANEXO B',
    'ULTIMA FACTURA ELECTRICA',
    'CARTA DE AUTORIZACION',
    'DIAGRAMA UNIFILAR',
    'POLIZA RC',
    'CARTA DE DESCRIPCION DE FINALIZACION',
    'CARTA DE NO OBJECION',
    'CARTA DE ACUERDO DE INTERCONEXION',
    'ACUERDO DE INTERCONEXION',
    'ACUERDO DE MEDICION NETA',
    'CARTA DE GARANTIA DE EQUIPOS',
    'CARTA DEL MEDIDOR',
    'CARTA AUTORIZACION DEL INGENIERO',
]

DOCUMENTS_SECTION_CNE = [
    'FORMULARIO FO-DIL 003',
    'FORMULARIO FO-DIL 005',
    'COTIZACION HACIENDA',
    'HOJA DE DATOS',
    'RESOLUCION CNE DE ITBIS',
    'APROBACION DGI ITBIS',
    'FACTURA DEL PROYECTO',
    'RESOLUCION CNE DE CF',
    'APROBACION 1 DGI CF',
    'APROBACION 2 DGI CF',
    'APROBACION 3 DGI CF',
    'NEGACIONES',
    'CARTAS DE REINTRODUCCION',
    'COMPROBANTES DE PAGO',
    'CARTAS SOLICITUDES',
]


DOCUMENT_UPLOAD_BUCKET = 'installation-documents'
